backend:
  name: git-gateway
  branch: main # o master, dependiendo de tu rama principal

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "_posts/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título de la Noticia", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Principal", name: "image", widget: "image" }
      - { label: "Resumen (para la tarjeta)", name: "summary", widget: "text" }
      - { label: "Contenido Completo", name: "body", widget: "markdown" }

  - name: "proyectos"
    label: "Proyectos"
    folder: "_posts/proyectos"
    create: true
    fields:
      - { label: "Nombre del Proyecto", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Comunidad", "Medio Ambiente", "Salud", "Desarrollo Profesional"] }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Resumen", name: "summary", widget: "text" }
      - { label: "Contenido Completo (Opcional)", name: "body", widget: "markdown", required: false }
  
  # La sección de "Actas" empieza aquí, al mismo nivel que "proyectos" y "noticias"
  - name: "actas"
    label: "Actas de Reunión"
    folder: "_posts/actas"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-acta"
    fields:
      - { label: "Título del Acta (Ej: Acta Reunión Julio 2025)", name: "title", widget: "string" }
      - { label: "Fecha del Acta", name: "date", widget: "date" }
      - { label: "Archivo PDF (Opcional)", name: "pdf", widget: "file", required: false }
      - { label: "Contenido del Acta (Si no subes PDF)", name: "body", widget: "markdown", required: false }